name: loan_app
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
    cached_network_image: ^3.1.0+1
    carousel_slider: ^4.0.0
    cupertino_icons: ^1.0.3
    
    dartz: ^0.10.0
    device_preview: ^1.0.0
    dio: ^4.0.4
    firebase_core: any
    dio_http_cache: ^0.3.0
    event_bus: ^2.0.0
    external_app_launcher: ^2.0.1
    firebase_analytics: ^9.1.0
    # firebase_core: ^1.12.0
    firebase_crashlytics: ^2.5.1
    firebase_database: ^9.0.9
    firebase_messaging: ^11.2.6
    firebase_performance: ^0.8.0+5
    firebase_remote_config: ^2.0.0
    flag: ^5.0.1


    flutter:
        sdk: flutter
    flutter_local_notifications: ^9.2.0
  
    flutter_localizations:
        sdk: flutter
    flutter_smartlook: ^3.0.6
    flutter_svg: ^1.0.3
    fluttericon: ^2.0.0
    get_it: ^7.2.0
    hive: ^2.0.4
    hive_flutter: ^1.1.0
    in_app_update: ^3.0.0
    intl: ^0.17.0
    jwt_decoder: ^2.0.1
    mocktail: ^0.2.0
    package_info: ^2.0.2
    permission_handler: ^8.1.4
    pin_code_fields: ^7.3.0
    provider: ^6.0.1
    share_plus: ^3.0.4
    shimmer: ^2.0.0
    url_launcher: ^6.0.12
    uuid: ^3.0.5

dependency_overrides:
    analyzer: ^3.2.0
    json_annotation: ^4.4.0

dev_dependencies:
    dart_code_metrics: ^4.1.0
    flutter_launcher_icons: ^0.9.2
    flutter_test:
        sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/logo.jpg"



flutter:

    uses-material-design: true
    assets:
        - assets/images/
        - assets/l10n/
        - assets/icons/